ALPHA = 3.0
IMG_NROWS = 224
IMG_NCOLS = 224
CONTENT_IMAGE_PATH = 'content/2.jpg'
STYLE_IMAGE_PATH = 'style/4.jpg'
CONTENT_WEIGHT = 1e4
STYLE_WEIGHT = 1e-3
TOTAL_VARIATION_WEIGHT = 30
ITERATIONS = 300
PREFIX = "result/"

